package dev.spaghetti.ai

/** Builds the Markdown content of `MANIFEST.md` -- pure text, no I/O, so it's testable on its own. */
object ManifestWriter {

    fun render(sourceFileName: String, summaries: List<FileSummary>): String {
        val header = "# Untangled: $sourceFileName\n\n" +
            "Where to look if you want to change something. Generated by OpenAI; the code itself was " +
            "never touched by AI -- only cut and moved, verbatim, by the plugin's own parser.\n\n" +
            "| File | What's in it |\n|---|---|\n"
        val rows = summaries.joinToString("\n") { "| `${it.path}` | ${it.summary.replace("|", "\\|")} |" }
        return header + rows + "\n"
    }
}
